language: python

python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install blender

install:
  - wget http://mirror.cs.umn.edu/blender.org/release/Blender2.75/blender-2.75-linux-glibc211-x86_64.tar.bz2
  - tar jxf blender-2.75-linux-glibc211-x86_64.tar.bz2
  - sh tests/install_sample.sh samples blender-2.75-linux-glibc211-x86_64/2.75/scripts/addons

script: blender-2.75-linux-glibc211-x86_64/blender -noaudio --factory-startup --background --python tests/test_sample.py
