language: python

python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install blender

install:
  - mkdir tmp && cd tmp
  - wget http://mirror.cs.umn.edu/blender.org/release/Blender2.75/blender-2.75-linux-glibc211-x86_64.tar.bz2
  - tar jxf blender-2.75-linux-glibc211-x86_64.tar.bz2
  - mv blender-2.75-linux-glibc211-x86_64 blender
  - rm blender-2.75-linux-glibc211-x86_64.tar.bz2
  - cd ..

script: 
